- name: Install bspwm packages
  become: true
  apt:
    name:
      - bspwm
      - suckless-tools
      - libinput-tools
    state: latest
  when: only_sync_files != "yes"
- name: Create dir structure
  file:
    state: directory
    recurse: yes
    path: ~/.config/bspwm
  when: only_sync_files != "yes"
- name: Copy bspwm configuration files
  ansible.builtin.template:
    mode: 0775
    src: ./files/bspwmrc.j2
    dest: ~/.config/bspwm/bspwmrc
- name: Reload bspwm
  shell: /usr/bin/bspc wm -r 2> /dev/null || exit 0
