#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom -f --daemon --config "$HOME/.config/picom/picom.conf" &
# pgrep -x polybar > /dev/null || $HOME/.config/polybar/yuki/launch.sh &
bspc config -m eDP top_padding 44
pgrep -x eww > /dev/null || eww open-many bar &
pgrep -x dunst > /dev/null || dunst &
feh --bg-fill ~/.config/wallpapers/wallpaper.jpg &
xsetroot -cursor_name left_ptr

bspc monitor -d I II III IV V VI VII VIII
bspc config pointer_motion_interval 60
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_motion_interval 5

bspc rule -a kitty desktop=I follow=off -o
bspc rule -a code desktop=II state=monocle follow=off -o
bspc rule -a google-chrome desktop=III state=monocle follow=off -o

[ "$1" = 0 ] && { 
    sleep 1
    kitty &
    code &
    google-chrome &
}