- name: Check if already is installed
  stat:
    path: ~/.local/bin/eww
  register: eww_installed
  when: only_sync_files != "yes"

- become: true
  when: not eww_installed.stat.exists
  block:
    - name: Install related packages
      apt:
        name:
          - libgtk-3-0
          - libgtk-3-dev
          - libgtk-layer-shell0
          - libgtk-layer-shell-dev
          - gtk-layer-shell-examples
          - libpango-1.0-0
          - libpango1.0-dev
          - libpangoft2-1.0-0
          - libpangocairo-1.0-0
          - libgdk-pixbuf-2.0-0
          - libgdk-pixbuf-2.0-dev
          - libgdk-pixbuf2.0-bin
          - libdbusmenu-gtk3-4
          - libdbusmenu-gtk3-dev
          - libcairo2
          - libcairo-gobject2
          - libcairo2-dev
          - libglib2.0-0
          - libglib2.0-bin
          - libglib2.0-dev
          - libgio-2.0-0
          - libgobject-2.0-0
          - libgcc-s1
          - build-essential
          - libc6
          - libc6-dev
          - locales
          - cargo
        state: present

- when:
    - only_sync_files != "yes"
    - not eww_installed.stat.exists
  block:
    - name: Download eww source
      get_url:
        url: https://github.com/elkowar/eww/archive/refs/tags/v{{ eww_version }}.tar.gz
        dest: /tmp/eww.tar.gz
      retries: 3
      delay: 5
    - name: Extract eww source
      unarchive:
        src: /tmp/eww.tar.gz
        dest: /tmp/
        remote_src: yes
    - name: Build eww
      shell: |
        cd /tmp/eww-{{ eww_version }}
        cargo build --release --no-default-features --features x11
    - name: Create dir structure
      file:
        state: directory
        recurse: yes
        path: ~/.config/eww
      loop:
        - ~/.config/eww
        - ~/.local/bin/eww
    - name: Move binary to /bin
      copy:
        src: /tmp/eww-{{ eww_version }}/target/release/eww
        dest: ~/.local/bin/eww
        remote_src: yes
        mode: 0775
    - name: Remove build folder
      file:
        path: /tmp/eww-{{ eww_version }}
        state: absent
    - name: Remove downloaded tarball
      file:
        path: /tmp/eww.tar.gz
        state: absent
      when: only_sync_files != "yes"

- name: Copy eww configuration files
  copy:
    mode: "preserve"
    src: ./files/config/
    dest: ~/.config/eww

- name: Update .profile
  lineinfile:
    dest: ~/.profile
    line: "export XDG_CONFIG_HOME=~/.config"

#- name: Reload eww
#  shell: ~/.local/bin/eww reload
