#!/bin/sh
workspaces() {

ws1="I"
ws2="II"
ws3="III"
ws4="IV"
ws5="V"
ws6="VI"
ws7="VII"
ws8="VIII"

# Unoccupied
un="0"

# check if Occupied
o1=$(bspc query -D -d .occupied --names | grep -E "^$ws1$" )
o2=$(bspc query -D -d .occupied --names | grep -E "^$ws2$" )
o3=$(bspc query -D -d .occupied --names | grep -E "^$ws3$" )
o4=$(bspc query -D -d .occupied --names | grep -E "^$ws4$" )
o5=$(bspc query -D -d .occupied --names | grep -E "^$ws5$" )
o6=$(bspc query -D -d .occupied --names | grep -E "^$ws6$" )
o7=$(bspc query -D -d .occupied --names | grep -E "^$ws7$" )
o8=$(bspc query -D -d .occupied --names | grep -E "^$ws8$" )

# check if Focused
f1=$(bspc query -D -d focused --names | grep -E "^$ws1$" )
f2=$(bspc query -D -d focused --names | grep -E "^$ws2$" )
f3=$(bspc query -D -d focused --names | grep -E "^$ws3$" )
f4=$(bspc query -D -d focused --names | grep -E "^$ws4$" )
f5=$(bspc query -D -d focused --names | grep -E "^$ws5$" )
f6=$(bspc query -D -d focused --names | grep -E "^$ws6$" )
f7=$(bspc query -D -d focused --names | grep -E "^$ws7$" )
f8=$(bspc query -D -d focused --names | grep -E "^$ws8$" )

ic_1=""
ic_2=""
ic_3=""
ic_4=""
ic_5=""
ic_6=""
ic_7=""
ic_8=""
if [ $f1 ]; then
    ic_1=""
elif [ $f2 ]; then
    ic_2=""
elif [ $f3 ]; then
    ic_3=""
elif [ $f4 ]; then
    ic_4=""
elif [ $f5 ]; then
    ic_5=""
elif [ $f6 ]; then
    ic_6=""
elif [ $f7 ]; then
    ic_7=""
elif [ $f8 ]; then
    ic_8=""
fi

# echo "
# cat << EOF
# (box :class "works"	
#      :orientation "h" 
#      :spacing 5 
#      :space-evenly "true" 
# (button :onclick "bspc desktop -f $ws1"	
#         :class	"work$un$o1$f1"	"$ic_1") 
# (button :onclick "bspc desktop -f $ws2"	
#         :class "work$un$o2$f2"	 "$ic_2") 
# (button :onclick "bspc desktop -f $ws3"	
#         :class "work$un$o3$f3" "$ic_3") 
# (button :onclick "bspc desktop -f $ws4"	
#         :class "work$un$o4$f4"	"$ic_4") 
# (button :onclick "bspc desktop -f $ws5"	
#         :class "work$un$o5$f5" "$ic_5")  
# (button :onclick "bspc desktop -fs $ws6"	
#         :class "work$un$o6$f6" "$ic_6")  
# (button :onclick "bspc desktop -f $ws7"	
#         :class "work$un$o7$f7" "$ic_7") 
# (button :onclick "bspc desktop -f $ws8"	
#         :class "work$un$o8$f8" "$ic_8")
# )
# EOF
# Its is a line because it gets like a tail of the script
cat << EOF
(box :class "works"	      :orientation "h"       :spacing 5       :space-evenly "true"  (button :onclick "bspc desktop -f $ws1"	         :class	"workspace-dot"	"$ic_1")  (button :onclick "bspc desktop -f $ws2"	         :class "workspace-dot"	 "$ic_2")  (button :onclick "bspc desktop -f $ws3"	         :class "workspace-dot" "$ic_3")  (button :onclick "bspc desktop -f $ws4"	         :class "workspace-dot"	"$ic_4")  (button :onclick "bspc desktop -f $ws5"	         :class "workspace-dot" "$ic_5")   (button :onclick "bspc desktop -fs $ws6"	         :class "workspace-dot" "$ic_6")   (button :onclick "bspc desktop -f $ws7"	         :class "workspace-dot" "$ic_7")  (button :onclick "bspc desktop -f $ws8"	         :class "workspace-dot" "$ic_8") )
EOF
# )"

}
workspaces

bspc subscribe desktop node_transfer | while read -r _ ; do
    workspaces
done
