#!/bin/bash

echo "input: $1" >> /tmp/log

CURRENT_WORKSPACE=$(bspc query -D -m last -d focused --names)
MONITOR=$(bspc query -M --names | head -1)

if [ "$1" = "prev" ]; then
    NEXT_WORKSPACE=$(bspc query -D --names | grep -E "^$CURRENT_WORKSPACE$" -B 1 | grep -vE "^$CURRENT_WORKSPACE$") 
    echo "prev:workspace $CURRENT_WORKSPACE $MONITOR $1 $NEXT_WORKSPACE" >> /tmp/log
    if [ -z $NEXT_WORKSPACE ]; then  
        NEXT_WORKSPACE=$(bspc query -D --names | tail -1)
    fi
fi

if [ "$1" = "next" ]; then
    NEXT_WORKSPACE=$(bspc query -D --names | grep -E "^$CURRENT_WORKSPACE$" -A 1 | grep -vE "^$CURRENT_WORKSPACE$") 
    echo "next:workspace $CURRENT_WORKSPACE $MONITOR $1 $NEXT_WORKSPACE" >> /tmp/log
    if [ -z $NEXT_WORKSPACE ]; then  
        NEXT_WORKSPACE=$(bspc query -D --names | head -1)
    fi
fi

if [ $1 -ge 1 ] && [ $1 -le 8 ]; then
    NEXT_WORKSPACE=$(bspc query -D --names | grep -vE "^(l|r).*" | sed -n "$1p")
    echo "number:workspace $CURRENT_WORKSPACE $MONITOR $1 $NEXT_WORKSPACE" >> /tmp/log
fi

NEXT_WORKSPACE=$(echo $NEXT_WORKSPACE | tr -d 'l' | tr -d 'r')
echo "changing:workspace $NEXT_WORKSPACE" >> /tmp/log

echo "changing:desktop $NEXT_WORKSPACE" >> /tmp/log
bspc desktop -a $NEXT_WORKSPACE

if bspc query -D --names | grep -qE "^l.*" ; then
    echo "changing:desktop l$NEXT_WORKSPACE" >> /tmp/log
    bspc desktop -a l$NEXT_WORKSPACE
fi
if bspc query -D --names | grep -qE "^r.*" ; then
    echo "changing:desktop r$NEXT_WORKSPACE" >> /tmp/log
    bspc desktop -a r$NEXT_WORKSPACE
fi


if echo $CURRENT_WORKSPACE | grep -qE "^l.*" ; then
    bspc desktop -f l$NEXT_WORKSPACE
elif echo $CURRENT_WORKSPACE | grep -qE "^r.*" ; then
    bspc desktop -f r$NEXT_WORKSPACE
else
    bspc desktop -f $NEXT_WORKSPACE
fi
